// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRt5PiIQPkPm1BhBj5vaVmgetU44PqCig',
    appId: '1:1020541347977:web:0abd2be03957fc986ffe58',
    messagingSenderId: '1020541347977',
    projectId: 'auto-customer-care',
    authDomain: 'auto-customer-care.firebaseapp.com',
    storageBucket: 'auto-customer-care.appspot.com',
    measurementId: 'G-9237T3M5FP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA579CNtNHPT7o2i490nyLkF6WmYIQ-BSc',
    appId: '1:1020541347977:android:a2b7fac4ec0809f46ffe58',
    messagingSenderId: '1020541347977',
    projectId: 'auto-customer-care',
    storageBucket: 'auto-customer-care.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKIDNi2qOx3-ima4MffigFRMC5ANCtMAs',
    appId: '1:1020541347977:ios:e1782350cee3d7066ffe58',
    messagingSenderId: '1020541347977',
    projectId: 'auto-customer-care',
    storageBucket: 'auto-customer-care.appspot.com',
    iosClientId: '1020541347977-7t6av41q8mal71g5j4oni9hmnkq504o9.apps.googleusercontent.com',
    iosBundleId: 'com.andynspecial.autoCustomerCareApp',
  );
}
